# Generated by Django 5.1.4 on 2024-12-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Category',
            field=models.ManyToManyField(related_name='Articles', to='home.category', verbose_name='دسته بندی'),
        ),
    ]
